### ISSUE TITLE
Request `scanpollinginterval` to be added

### ISSUE THREAD

**Issue by Honest-Objections** [veracode/veracode-uploadandscan-action#36]
120 seconds to poll can feel far too slow in our pipelines. 

Any chance [`scanpollinginterval`](https://docs.veracode.com/r/r_uploadandscan) could be added?

**Comment by julz0815** [comment]
[scanpollinginterval](https://docs.veracode.com/r/r_uploadandscan) is now supported on the latest version of the action

**Comment by julz0815** [comment]
closed
