### ISSUE TITLE
v1.0 refers to an old release

### ISSUE THREAD

**Issue by marcus-bcl** [veracode/veracode-uploadandscan-action#45]
We recently got a Dependabot PR (https://github.com/ministryofjustice/hmpps-probation-integration-services/pull/3619) attempting to upgrade our action version from [0.2.6](https://github.com/veracode/veracode-uploadandscan-action/releases/tag/0.2.6) to [v1.0](https://github.com/veracode/veracode-uploadandscan-action/releases/tag/v1.0), however it appears [v1.0](https://github.com/veracode/veracode-uploadandscan-action/releases/tag/v1.0) refers to an older commit from 26/08/2020.

Should this tag be removed or renamed?

**Comment by brendanlafond** [comment]
Same is happening for all GitHub Dependabot users. Please remove or rename the initial release from 2020, which is labeled v1.0.
![image](https://github.com/veracode/veracode-uploadandscan-action/assets/85505422/5bd614c1-6109-4ff3-a178-5401f74c3f7d)

**Comment by julz0815** [comment]
this has been changed now
